#include <iostream>
using namespace std;
main(){
int num1;
int num2;
int num3;
int num4;
int num5;
int num6;
int num7;
int num8;
int num9;
int num10;
int add;
int subtract;
float divide;
int multiply;
float result;
cout <<"enter num1";
cin >>num1;
cout <<"enter num2";
cin >>num2;
cout <<"enter num3";
cin >>num3;
cout <<"enter num4";
cin >>num4;
cout <<"enter num5";
cin >>num5;
cout <<"enter num6";
cin >>num6;
cout <<"enter num7";
cin >>num7;
cout <<"enter num8";
cin >>num8;
cout <<"enter num9";
cin >>num9;
cout <<"enter num10";
cin >>num10;
add = num1 + num2 + num3 + num4;
cout<<"Addition is:";
cout<<add<<endl;
subtract = num5 -num6;
cout<<"Subtraction is:";
cout<<subtract<<endl;
divide = num7/num8;
cout<<"Division is:";
cout<<divide<<endl;
multiply =num9*num10;
cout<<"Multiplication is:";
cout<<multiply;
}